kind: Pod
apiVersion: v1
metadata:
  name: web-server-pod
spec:
  containers:
    - name: frontend
      image: nginx
      volumeMounts:
      - mountPath: "/etc/nginx/htpasswd"
        name: cred-volume
        subPath: htpasswd
      - mountPath: "/etc/nginx/conf.d/default.conf"
        name: config-volume
        subPath: default.conf
  volumes:
    - name: cred-volume
      secret:
        secretName: nginx-secret
    - name: config-volume
      configMap:
        name: nginx-config-alt
