apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: student14-nfs-pv
