apiVersion: v1
kind: PersistentVolume
metadata:
  name: student14-nfs-pv
  labels:
    name: student14-nfs-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 34.138.155.87
    path: /
