apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-app
  name: app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: http-app
  sessionAffinity: None
  type: LoadBalancer
