apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: http-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
      - name: http-app
        image: acmeade/http-app:v2
        ports:
        - containerPort: 80
